/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StoreDemo {
        "start": number;
    }
    interface StoreDemoChild {
    }
}
declare global {
    interface HTMLStoreDemoElement extends Components.StoreDemo, HTMLStencilElement {
    }
    var HTMLStoreDemoElement: {
        prototype: HTMLStoreDemoElement;
        new (): HTMLStoreDemoElement;
    };
    interface HTMLStoreDemoChildElement extends Components.StoreDemoChild, HTMLStencilElement {
    }
    var HTMLStoreDemoChildElement: {
        prototype: HTMLStoreDemoChildElement;
        new (): HTMLStoreDemoChildElement;
    };
    interface HTMLElementTagNameMap {
        "store-demo": HTMLStoreDemoElement;
        "store-demo-child": HTMLStoreDemoChildElement;
    }
}
declare namespace LocalJSX {
    interface StoreDemo {
        "start"?: number;
    }
    interface StoreDemoChild {
    }
    interface IntrinsicElements {
        "store-demo": StoreDemo;
        "store-demo-child": StoreDemoChild;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "store-demo": LocalJSX.StoreDemo & JSXBase.HTMLAttributes<HTMLStoreDemoElement>;
            "store-demo-child": LocalJSX.StoreDemoChild & JSXBase.HTMLAttributes<HTMLStoreDemoChildElement>;
        }
    }
}
